author: ShangYin # 作者
description: shangyin's blog
keyword: golang
favicon:

excerpt_link: ">> Read more >>"

menu:
  主页: /
  标签: /tags/
  归档: /archives/
  工具: /tools/
  # Projects: /project/
  关于我: /about/

# highlight
highlight: xcode

# catalog
catalog: true

# donate
donate: false

# qrcode
qrcode: false

# comment
# you can set gitment, uyan or disqus

comment: gitment

# gitment config
gitment_owner: ShangYin
gitment_repo: ShangYin.github.io
gitment_oauth_id: 0f87e490e00ee3fd87ef
gitment_oauth_secret: 4a9d2b148e7971c2201ad12131ce8bf8159ccd2e

# uyan config
# if you want to use uyan as your blog comment, plz remove/comment out gitment config
baidu_id:

# disqus config
disqus_shortname:

about:
  banner: http://file.muyutech.com/about.jpg
  avatar: https://avatars3.githubusercontent.com/u/16443628?v=3&s=460
  description: "明天会更好"
  weibo_username: ShangYin
  # twitter_username: ShangYin
  github_username: Shangyin666
  # zhihu_username: yummy1121
  # douban_username: ShangYin
  # linkedin_username:

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML
